language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages:git
  local_dir: src/.vuepress/dist
  token: $GITHUB_TOKEN
  repo: meteostat/meteostat.github.io
  target_branch: master
  fqdn: dev.meteostat.net
  on:
    branch: main
